include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    - always_declare_return_types
    - require_trailing_commas
    - unnecessary_raw_strings
    - use_decorated_box

analyzer:
  errors:
    deprecated_member_use_from_same_package: ignore
  exclude:
    - lib/src/l10n/**
    # Remove the below directory until migration is complete.
    - example/**
    - test/**
    - lib/src/service/**
